docs_dir: docs/book
site_dir: docs/html
nav:
    - Home: index.md
    - v3:
        - Introduction: v3/intro.md
        - Installation: v3/installation.md
        - "Basic Usage": v3/usage.md
        - Configuration: v3/configuration.md
        - "Advanced Usage": v3/advanced.md
        - "Caching Paginator Pages": v3/caching.md
        - 'Application Integration':
            - 'Stand-Alone': v3/application-integration/stand-alone.md
        - 'Migration':
            - 'From v2 to v3': v3/migration/from-v2-to-v3.md
    - v2:
        - Introduction: v2/intro.md
        - Installation: v2/installation.md
        - Usage: v2/usage.md
        - Configuration: v2/configuration.md
        - "Advanced Usage": v2/advanced.md
        - 'Application Integration':
            - 'Stand-Alone': v2/application-integration/stand-alone.md
site_name: laminas-paginator
site_description: 'Paginate collections of data from arbitrary sources'
repo_url: 'https://github.com/laminas/laminas-paginator'
extra:
    project: Components
    installation:
        config_provider_class: 'Laminas\Paginator\ConfigProvider'
    current_version: v3
    versions:
        - v3
        - v2
plugins:
    - redirects:
          redirect_maps:
              intro.md: v3/intro.md
              installation.md: v3/installation.md
              usage.md: v3/usage.md
              configuration.md: v3/configuration.md
              advanced.md: v3/advanced.md
              application-integration/stand-alone.md: v3/application-integration/stand-alone.md
